### ISSUE TITLE
Farbschema

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-Philfak#1]
Auf der Fehlerseite passt das Farbschema nicht. Siehe screenshot.
![bildschirmfoto 2015-04-08 um 16 38 57](https://cloud.githubusercontent.com/assets/11296947/7047607/df7c0cf2-de0d-11e4-84f2-c33115935146.png)

**Comment by xwolfde** [comment]
ok, merk ich mir. Ich mach das mit dem Repo aber hier anders, deswegen erstmal close
