### ISSUE TITLE
Übersicht der vorhandenen Abonnements fehlt

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/FAU-Philfak#10]
siehe Screenshot
![bildschirmfoto 2015-04-17 um 14 47 47](https://cloud.githubusercontent.com/assets/11868989/7202271/06e94002-e511-11e4-8924-b77362923bb7.png)

**Comment by xwolfde** [comment]
Termin-Plugin für @rvdforst

**Comment by xwolfde** [comment]
Bei mir gehts?  
Ein Abo ist natürlich nur da, wenn du es vorher angelegt hast....

**Comment by steffigebel** [comment]
Right!
