### ISSUE TITLE
Link zur englischsprachigen Fakultätsseite

### ISSUE THREAD

**Issue by pdees** [RRZE-Webteam/FAU-Philfak#101]
Die Homepage der PhilFak ist mittlerweile auf Englisch verfügbar. Wenn ich das richtig sehe, wird der Link im Topmenü aber nirgendwo im Backend eingestellt, sondern direkt im Theme aus Metadaten generiert. Entsprechend müsste das für die Sprachversion "Englisch" auf phil.fau.eu geändert werden.

**Comment by AstridSemm** [comment]
Der Sprachumschalter ist ein Widget, das entsprechend aktiviert wird; soweit ich sehen kann, haben die Administratoren der Phil-Seiten das auch korrekt gemacht. Nachdem der issue auch schon seit sieben Tagen liegt, schließe ich ihn jetzt. Bei Rückfragen kann er ja wieder geöffnet werden.

**Comment by AstridSemm** [comment]
Herr Filler rief gerade an und teilte mit, dass es gar nicht um den Sprachumschalter geht. Das Problem stellt sich dar wie folgt:
Es gibt Lehrstühle/Einrichtungen, die englischsprachige Homepages haben; die möchten natürlich gern, dass der Link im Metamenü oben, der ja fix auf die Fakultät geht, dann auch auf die englischsprachige Fakultätshomepage zeigt. Derzeit ist es wohl so, dass immer die Domain phil.fau.de hinterlegt ist, egal, welche Sprachversion.

**Comment by FlorianFiller** [comment]
Zur Erläuterung noch ein Screenshot: 
![link](https://cloud.githubusercontent.com/assets/12810141/22682873/94f8a12c-ed15-11e6-83d2-3de4fb395f9f.png)

Mit dem Sprachwechselbutton ändert sich sogar der Text von "Philosophische Fakultät" auf "Faculty of Philosophy", aber nicht der hinterlegte Link.

**Comment by FlorianFiller** [comment]
Das Problem ist immer noch vorhanden und immer noch aktuell.

**Comment by xwolfde** [comment]
Gab auch bisher kein Update :(

**Comment by AstridSemm** [comment]
Ah, hier ist der Issue. Dann schließe ich das Ticket im OTRS (https://helpdesk.rrze.uni-erlangen.de/otrs/index.pl?Action=AgentTicketZoom;TicketID=582563), weil's ja bereits bearbeitet wird.

**Comment by FlorianFiller** [comment]
Sie dürfen die Sache auch gerne verschieben, wenn es der Bearbeitung dient. 
Ggf. reicht ja ein kleiner "Hotfix" aus, um aus dem .de im englischen Theme ein .eu zu machen. =)

**Comment by xwolfde** [comment]
Wahrscheinlich wird es noch heute das update geben. Dieser Issue wird dabei mit behoben.
