### ISSUE TITLE
Beim Tabellen editieren weiße Schrift auf weißem Grund

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-Philfak#11]
Im WYSIWYG-Editor wird jede zweite Tabellenzeile korrekt mit weißem Hintergrund angezeigt - die Schrift ist dort aber auch weiß. In der Anzeige ist's dann wieder normal. Screenshots:
Editor:
![bildschirmfoto 2015-04-17 um 15 03 13](https://cloud.githubusercontent.com/assets/11296947/7202478/fea8db1c-e512-11e4-8e83-db63922d999b.png)
Ergebnis:
![bildschirmfoto 2015-04-17 um 15 03 35](https://cloud.githubusercontent.com/assets/11296947/7202482/056f0b6a-e513-11e4-825c-3ce8bca5d82c.png)

**Comment by xwolfde** [comment]
Neeeeneeeeneeee
