### ISSUE TITLE
Texteingabefeld könnte besser in Spalte passen 

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/FAU-Philfak#12]
Ist nichts Schlimmes... bin mir nicht sicher, ob das nicht FAk-übergreifend der Fall ist. 

![bildschirmfoto 2015-04-17 um 15 03 44](https://cloud.githubusercontent.com/assets/11868989/7202483/0bc966c2-e513-11e4-8cbc-837298fc645e.png)

**Comment by xwolfde** [comment]
fixed ;) Fies - das tritt ja nur auf, weil du die Mezabox an die Sidebar verschiben hast .
