### ISSUE TITLE
Beiträge - Beitragsbild

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/FAU-Philfak#15]
Hier wäre eine Erklärung beim Beitragsbild schön: z. B. 

Falls ein Beitrag ein Schlagwort/eine Kategorie enthält, das diesen auf der Startseite bzw im Slider anteasern lässt, so wird das Beitragsbild auch als Bühnenbild verwendet, sofern kein oder kein alternatives Bühnenbild eingesetzt wird (4:1, 1260*350px).

**Comment by xwolfde** [comment]
Wäre das nicht eher was für die Schulung? @AstridSemm ?

**Comment by AstridSemm** [comment]
Japp, sollten wir da mit reinnehmen. Wie setze ich mir hier ein Bookmark? Oder können wir ein Label "Schulung" basteln? Wenn ja: Wie? Hach, immer diese neuen Tools!

**Comment by steffigebel** [comment]
label ist drin @xwolfde @AstridSemm

**Comment by steffigebel** [comment]
Könnte man als geschulter aber dann auch schnell wieder vergessen, wenn mans nicht täglich umsetzt. daher war der vorschlag direkt ins system als hilfe reinzustellen

**Comment by AstridSemm** [comment]
Erledigt.
