### ISSUE TITLE
Doppelausgabe Kontakt (Sidebar)

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/FAU-Philfak#16]
Wählt man in der Auswahlbox für Ansprechpartner >1 Kontakte aus und füllt das Feld Ansprechpartner aus, so wird die Überschrift bei dem 2. Kontakt noch einmal aufgeführt. Wäre schön, wenn das vermieden werden kann. Siehe Screenshot. 
![bildschirmfoto 2015-04-23 um 16 39 26](https://cloud.githubusercontent.com/assets/11868989/7299626/553bcc1e-e9d7-11e4-9059-2065f9601026.png)

**Comment by xwolfde** [comment]
In der nächsten Verison behoben
