### ISSUE TITLE
Kontakte Sidebar

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/FAU-Philfak#17]
Es wäre von Vorteil, wenn Kontakte aus der Auswahlliste geordnet werden könnten, also in eine bestimmte Reihenfolge gebracht werden könnten. Das ist dann relevant, wenn es aufgrund unterschiedlicher Adresse aber gleicher Zuordnung keinen Sinn macht, eine Organisation als Kontakt anzulegen (also nur 1 Kontakt mit 2 Personen). Das ist z. B. wichtig bei 2 Ansprechpartnern zum gleichen Thema, die aber unterschiedliche Telefonnummern haben und auch an verschiedenen Orten sitzen, so dass es sinnvoller wäre, beide getrennt voneinander, also 2 Kontakte anzugeben. Siehe Beispiel. In diesem Fall ist es aber wichtig, dass man die Möglichkeit zur Ordnung an, denn hier wird z. B. die Übergeordnete Person unter der Referentin angeführt, was sicher zu Unmut seitens der Kunden führen wird ;-)

**Comment by xwolfde** [comment]
Siehe  #48
