### ISSUE TITLE
Hinweis für den Shortcode "Person einfügen" im Editor

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/FAU-Philfak#18]
Hier sollte statt slug="" id="" stehen. Vielleicht kann bitte noch im WIKI bzw in der readme erklärt werden, was showlink=0/1 bedeutet bzw extended="0" bedeutet und welche Möglichkeiten statt der default 0 noch eingesetzt werden können. 

Die Erklärung wäre auch bei allen anderen Shortcodes sehr hilfreich. Das sollten wir danna uch in die Hilfe im Backend für die Redakteure bereitstellen ;-)

**Comment by xwolfde** [comment]
id ist drin.
Doku der Shortcode-Funktionen von Kontakten muss noch kommen.
