### ISSUE TITLE
Galerie-Einstellungen kommen nirgends zum Tragen

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/FAU-Philfak#2]
Anscheinend kommen Änderungen der Daufault-Einstellungen oder selbst die Default Einstellungen selbst beim Erstellen von Galerien auf der Website nicht zum Tragen. Bsp: Eingabe Spaltenanzahl 3 oder auch 4 ergibt veröffentlicht keine Anzahl von Spalten, sondern nur den Slider. Ebenso verhält es sich bei der Angabe von  Größen der Bilder. 
Frage: Wo soll diese Einstellung zum Tragen kommen?  
![bildschirmfoto 2015-04-09 um 14 24 11](https://cloud.githubusercontent.com/assets/11868989/7067754/109404f0-dece-11e4-9340-de5b0917d6a0.png)
![bildschirmfoto 2015-04-09 um 14 30 29](https://cloud.githubusercontent.com/assets/11868989/7067753/10928990-dece-11e4-8822-71331bd5dc43.png)

**Comment by xwolfde** [comment]
Ich würde mal sagen...erstmal jedenfalls... war so gewollt :) "Das war eine designerische Entscheidung".

**Comment by xwolfde** [comment]
Im nächsten Update behoben.
Allerdings wird bei einer Verlinkung auf das Bild nach wie vor nur die Bilddatei selbst verlinkt, nicht die Bildseite (Anhang-Seite). Auch wenn das gewählt ist.
