### ISSUE TITLE
Seitenüberschrift wird überlagert

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-Philfak#21]
Das Design enthält ja den Titel der jeweiligen Portalseiten; das kann dazu führen, dass die Seitenüberschrift überlagert wird, was nicht wirklich optimal ist. Wir haben diskutiert, ob man den Layer mit dem Portalseitentitel nicht einfach eins nach hinten schieben kann. Screenshot:
![bildschirmfoto 2015-04-27 um 14 02 50](https://cloud.githubusercontent.com/assets/11296947/7347217/852524c2-ece6-11e4-9cd4-6bbc005dd66d.png)

**Comment by xwolfde** [comment]
Im nächsten update behoben
