### ISSUE TITLE
Übergreifender Issue für alle Themes

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/FAU-Philfak#22]
Layout der Seiten

Fügen Sie immer einen Untertitel ein, das gibt dem Layout den Rahmen und sorgt dafür, dass der Einstiegstext nicht oben am Rand klebt. Durch den Untertitel bekommt die Seite unter dem Header einen Padding.
Style H2: 
 font-size: 24px;
 line-height: 28px;
 margin: 0;
 padding: 22px 0

Anregung für die Themes: Den Contentbereich im CSS so anpassen, dass - falls kein Untertitel gesetzt wird - ein Padding-top von 23 px gesetzt wird.

Siehe Screenshot mit padding-top 23 px. 
![bildschirmfoto 2015-04-28 um 11 57 24](https://cloud.githubusercontent.com/assets/11868989/7367190/e697cb94-ed9d-11e4-9f6f-a8d83947fc13.png)

**Comment by xwolfde** [comment]
fixed im nächsten Update
