### ISSUE TITLE
Akkordeon <p>Tags / Textdarstellung

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/FAU-Philfak#23]
WP macht transportiert die <p>-Tags an Stellen, die keinen Sinn ergeben. Ergo der Text wird manchmal so, manchmal anders dargestellt. Es geht hauptsächlich um die Schriftgröße und -art. Was WP macht ist das: aus "p content /p" macht es "content p /p". Es ist aber unklar, wann genau, es auftritt und daher buggy. Manche Rollenprofile sehen keinen Text/html-Editor vor, daher sollte der Fehler behoben werden.

Wolfgang sagt, es ist ein Bug und kann behoben werden. 

https://phil.cms.rrze.uni-erlangen.de/fakultaet/gender-diversity/ Punkt 3 "Diversity Beauftragter"

**Comment by xwolfde** [comment]
Notiz: in bootstrap.php versteckt

**Comment by xwolfde** [comment]
fixed in nächster version
