### ISSUE TITLE
Fehlerhafte Ausgabe bei function fau_downloads 

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/FAU-Philfak#25]
https://www.fau.de/international/wege-ins-ausland/downloads-und-formulare-wia/downloads-wege-ins-ausland/
Es fehlt hier bei Downloads womöglich eine Ausgabe, falls ein Ordner leer ist. Der Nutzer denkt hier, es liegt ein Fehler vor, da die "Kategorien" keine Inhalte (=Downloads) liefern.

Man wünscht sich die Ausgabe: "Derzeit liegen keine Inhalte vor." 

Man müsste dazu wohl einmal die function fau_downloads( $atts, $content = null) prüfen.
![bildschirmfoto 2015-04-30 um 10 42 16](https://cloud.githubusercontent.com/assets/11868989/7409322/a35aaba6-ef25-11e4-9504-e419412af767.png)

**Comment by xwolfde** [comment]
Das Ding hat auch ein weiteers Problem durch Abhängigkeit: Es funktioniert nur, wenn das CMS-Settings Plugin aktiv ist. Denn nur dann kann man Medien taggen/kategorisieren.

**Comment by steffigebel** [comment]
Interessant. Hier ist es anscheinend an, da es unter dem Punkt Austauschprogramme greift.

**Comment by xwolfde** [comment]
Hier?

**Comment by steffigebel** [comment]
Im FAU-Theme

**Comment by xwolfde** [comment]
Wo?

**Comment by xwolfde** [comment]
Aus Recherche: Völlige Murksimplementierung. Wird erstmal aus dem Theme rausgeworfen und in Zukunft durch Plugin ersetzt.
