### ISSUE TITLE
Listeneinrückung

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-Philfak#26]
Bei längeren Listen mit mehrzeiligen Listenpunkten stimmt die Einrückung nicht. Siehe screenshot.
![bildschirmfoto 2015-05-05 um 08 48 53](https://cloud.githubusercontent.com/assets/11296947/7468035/d9b75cb2-f303-11e4-8bfb-5e23010a7d4c.png)

**Comment by xwolfde** [comment]
im nächsten update behoben
