### ISSUE TITLE
Sidebar bricht unter den Contentbereich um und steht nicht oben rechts

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/FAU-Philfak#27]
Link: https://phil.cms.rrze.uni-erlangen.de/fakultaet/die-fakultaet/studienzuschuesse/

![bildschirmfoto 2015-05-05 um 14 17 51](https://cloud.githubusercontent.com/assets/11868989/7472319/8bd1eec6-f331-11e4-9c03-b52d108e7a71.png)

**Comment by xwolfde** [comment]
Da war offenbar ein anderer fehler, der inzwischen gelöst wurde
