### ISSUE TITLE
Unterstützung shariff - Problem Theme bei Anzeige Share-Buttons

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/FAU-Philfak#28]
Aufzählungszeichen vor den Share-Buttons müssen weg ;-)
![bildschirmfoto 2015-05-06 um 14 58 27](https://cloud.githubusercontent.com/assets/11868989/7493406/db079340-f400-11e4-935b-b8515b8c8977.png)

**Comment by xwolfde** [comment]
Im GitHub gefixt, auf der CMS nach dem nächsten Update drin.
