### ISSUE TITLE
Mehr Meldungen und Mehr Veranstaltungen

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/FAU-Philfak#29]
Die Links "Mehr Meldungen" und "Mehr Veranstaltungen" werden auf der Startseite nicht angezeigt. Unter Theme Option ist das Häkchen zu "Weitere Meldungen verlinken." gesetzt. Müssen noch andere Angaben gemacht werden?

Gilt auch für FAU-NatFak

**Comment by xwolfde** [comment]
Jar, es muss immer auch noch die Kategorie gewählt werden, zu der verlinkt werden soll.
