### ISSUE TITLE
Nächste Termine Widget in Sidebar

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/FAU-Philfak#30]
Auswahl eines Filters wird ignoriert. Nach dem Häkchen setzen und abspeichern verschwindet Häkchen wieder. 

Dito für FAU-Theme und NatFak.

**Comment by xwolfde** [comment]
Ich verstehe diese Meldung nicht....

**Comment by cibsell** [comment]
Es kann sein, dass es das Plugin ist. Das kann ich als Anwender ja nicht sehen, woran das liegt. Ich eröffne das Issue aber auch gerne dort. Das Problem war bei einer alten FAU-PhilFak-Theme Version nicht, deshalb habe ich es hier vermerkt.

Neuer Erklärungsversuch:

In der Sidebar kann man das Widget Nächste Termine / News auf der Startseite anzeigen lassen. Das sieht so aus: 

![news-widget1](https://cloud.githubusercontent.com/assets/8234890/7509637/9fe938b6-f493-11e4-909e-a9fa15f2539f.png)

Ich kann hier zwar bei den Filtern ein Häkchen setzen, z. B. bei "Termine mit diesen Kategorien", aber es gibt keine Auswahlmöglichkeit, welche Kategorien ich anzeigen lassen möchte, und wenn ich auf "Speichern" gehe, dann ist das gesetzte Häkchen wieder fort.

**Comment by xwolfde** [comment]
Das Widget wird nicht auf der Startseite gezeigt, sondern auf den News-Indexseite. Also z.B. DOMAIN/category/allgemeines

Auf der Startseite wird in der Inline Sidebar ein Shortcode [termine cat="" anzahl=""] eingebaut.
