### ISSUE TITLE
Kann man auf der Startseite die Social- bzw. Media-Footer-Leiste rausnehmen?

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/FAU-Philfak#31]
PhilFak wünscht, die Leiste rauszunehmen, bzw. ohne inhalt darzustellen. Geht das oder ist per default immer etwas eingestellt?

**Comment by xwolfde** [comment]
Ja.
Unter "Theme Optionen->Social Media Footer" kann man einstellen, auf welchen Seiter der erscheinen soll.

**Comment by cibsell** [comment]
Wo stelle ich denn bei dieser Leiste ein, welche Videos angezeigt werden? Bei mir kommt, wenn ich unter Theme Options anklicke "Verlinke Videoportal auf dem Social Media Fußteil der Startseite" nur der Hinweis: "Fehlerhafte URL".

Kann ich z. B. einstellen, dass per Zufall aus dem Video-Pool der Naturw. Fakultät ausgewählt wird?

**Comment by xwolfde** [comment]
Den konkreten Inhalt des Bereichs rechts von den Social Media Icons machst du mit Hilfe des Widgets "Social Media Infobereich (Footer)" unter Design->Widgets. Da einfach reintun was du denkst. Textbereiche oder andere Widgets, Auch Shortcodes via Textwidget wäre möglich.

Eine Zufallswahl von Videos aus dem Videoportal haben wir derzeit noch nicht im Videoplugin (glaub ich).

**Comment by AstridSemm** [comment]
Beides ist dokumentiert, steht nur noch die Entscheidung aus, wohin es gehängt werden soll. Der issue kann aber geschlossen werden. Hurra!
