### ISSUE TITLE
Titel für Personen-Listen im Contentbereich

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/FAU-Philfak#32]
Es wäre schön, wenn man aufgrund besserer Einheitlichkeit im Shortcode zusätzlich einstellen kann, welches Listenelement (zum Beispiel das erste) eine default-Überschrift (z. B. h3) bekommt. 

Hintergrund: Im Contentbereich können via Shortcode Kontakte eingebunden werden, die mit einer Überschrift (KOntakt, Ansprechpartner) gekennzeichnet werden. Die Überschrift wird aber meist im Editor unformatiert eingegeben. Das sieht optisch nicht schön aus und hat den NAchteil, dass manche Ansprechpartner, manche Kontakt, manche Kontakte oder was ganz anderes eingeben. Schön wäre eine Lösung wie in der Sitebar (designtechnisch). Da es nicht via CSS eingebunden werden kann, wäre eine Einstellung zb im Shortcode "title=1" (gibt Titel kontakt an mit Format h3)

**Comment by xwolfde** [comment]
wird über neue Shortcodes mit bereit gestellt: https://github.com/RRZE-Webteam/fau-person/issues/60
