### ISSUE TITLE
Anpassungen bei Überschriften ab h3 in Akkordeons

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/FAU-Philfak#33]
Ab h3 die Überschriften im CSS anpassen Prüfen, ob die Farbe in den Farbcode passt, ansonsten eine ähnliche Farbe wählen. Beispiel auf dieser Seite https://phil.cms.rrze.uni-erlangen.de/lehre/studienangebot/bachelor/ unter Orientalistik. 
![bildschirmfoto 2015-05-12 um 15 21 01](https://cloud.githubusercontent.com/assets/11868989/7588011/8701b37a-f8ba-11e4-94bf-967b980f0b61.png)

**Comment by xwolfde** [comment]
Im nächsten Update gefixt
