### ISSUE TITLE
Bildunterschrift in unterschiedlichen Farben

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-Philfak#34]
Wenn man in einem Beitrag ein Beitragsbild einbindet, wird es rechts oben im Beitrag eingebunden und die Bildunterschrift ist schwarz.
![bildschirmfoto 2015-05-13 um 13 52 06](https://cloud.githubusercontent.com/assets/11296947/7609827/73cd01fc-f977-11e4-884c-d3d5fe44de60.png)
Bindet man dasselbe Bild als Datei im Beitrag ein, ist die Bildunterschrift golden.
![bildschirmfoto 2015-05-13 um 13 52 17](https://cloud.githubusercontent.com/assets/11296947/7609837/8972ea94-f977-11e4-8022-da156cfc1565.png)
Hier wäre meiner Ansicht nach eine einheitliche Schriftfarbe (nämlich die des Fließtextes, also schwarz) günstiger. Kann man das anpassen?

**Comment by xwolfde** [comment]
Ich weiss garnicht ob das so gewollt war oder nicht....

**Comment by xwolfde** [comment]
In Klärung. Ich finde es auch falsch

**Comment by xwolfde** [comment]
Ist Bug.

**Comment by xwolfde** [comment]
In nächster Version gefixt
