### ISSUE TITLE
Nicht-Zuklappen des letzten [collapse] bei Öffnen eines [collapse] eines neues [collapsibles]

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/FAU-Philfak#35]
Hier müsste das letzte zuklappen, auch wenn ein neues Akkordeon aufgeklappt wird. (Meiner Meinung nach)

https://phil.cms.rrze.uni-erlangen.de/lehre/studienangebot/master/
![bildschirmfoto 2015-05-13 um 15 36 48](https://cloud.githubusercontent.com/assets/11868989/7611654/18d28ff6-f986-11e4-9076-7f06d92128a0.png)

**Comment by xwolfde** [comment]
Wenn ich das richtig verstehe: 
Sind zwei unterschiedliche Accordions. Die kennen sich gegenseitig nicht un könnnen sich daher auch nicht beeinflussen. Du musst in einen Accordion bleiben, aber nicht mehrere auf der Site haben.
