### ISSUE TITLE
Seitentemplate startseite

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/FAU-Philfak#36]
Es gibt die Möglichkeit über Kategorien mithilfe des startseite-Seitentemplates Blog-Beiträge zu filten, so dass bestimmte Einträge nicht auf der Startseite (sondern z. B. auf Unterseiten) angezeigt werden. 

Dafür gebe ich einem bestimmten Beitrag die Kategorie "startseite". Wenn der Beitrag als großer Aufmacher in der Bühne erscheinen soll, dann muss die Kategorie "allgemein" gewählt werden.

Gibt es eine Möglichkeit die "Bühne" (also Blog-Beitrag als großen Aufmacher und die Linklisten der Bühne) abzuschalten? Gebe ich keinen Blog-Beitrag die Kategorie "allgemein", dann erscheint die Bühne als leeres, weißes Feld, die Linklisten bleiben erhalten.

**Comment by xwolfde** [comment]
Momentan ist das nicht vorgesehen, das die Bühne auf eine leere Kategorie gesetzt wird...
Ist ja eigentlich dann auch ein Bedienfehler.
Ggf. sollten wir da aber ein fallback-Verhalten einbauen.

**Comment by xwolfde** [comment]
Mooooment.
Bühne und Liste der News darunter sind doch unabhängig voneinander.
D.h. nur weil etwas als "startseite1" getaggt ist, muss es nicht in der Bühne auftauchen. In der Bühne taucht nur auf was in der für die Bühne definierten Kategorie ist.

Wenn die Frage dahin geht, ob wir nicht ein Template machen können, wo die Bühne fest ist un dnicht ein wechselndes Bild: Machen wir, Kommt :) Aber das ist ne andere Sache.
