### ISSUE TITLE
RSS Feed einbinden

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/FAU-Philfak#37]
Mir wurde von der Webredaktion folgender Shortcode für das Einbinden von Feeds genannt: 

[rss url=’ ’ items=”8″ show_title=”0″ show_description=”1″ show_author=”0″ show_date=”1″ show_source=”0″]

Wenn ich diesen Shortcode in einem Seitentemplate (Standard, Inhaltsseite mit Navi) eingebe, dann wird der Shortcode als Text angezeigt. Blogbeiträge werden nicht angezeigt. Nur mit dem Seitentemplate Startseite werden die Blogbeiträge korrekt und z. B. nach Kategorien gefiltert angezeigt. Da habe ich aber die Bühne im Template, die ich auf einer Unterseite (z. B. eine Unterseite mit Blog-Einträgen über Schüler-Events) nicht haben will.

Ist der Shortcode korrekt, muss ich etwas anderes eingeben, damit ich - nach Kategorien gefiltet - Blogeinträge auf Unterseiten anzeigen lassen kann?

**Comment by xwolfde** [comment]
Dazu musste das notwendige Plugin aktiviert sein, welches den Shortcode umsetzt. 
@rvdforst welches war das noch? Wo kriegt man das her, wenn man nicht auf der CMS ist?

**Comment by xwolfde** [comment]
Siehe https://www.wordpress.rrze.fau.de/plugins/rrze-rss-plugin/

**Comment by steffigebel** [comment]
Klappt das jetzt, Frau Sell? Ist das Plugin aktiviert, es ist das rrze-shortcodes-plugin. https://github.com/RRZE-Webteam/rrze-shortcodes

**Comment by cibsell** [comment]
Ja, das geht jetzt. Danke!
