### ISSUE TITLE
Redakteure bekommen keine Anmelde-Mails

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/FAU-Philfak#39]
Wenn ich als Admin einen Redakteur anlege, bekommt der keine Mails. Wenn mich jemand als Admin anlegt, bekomme ich schon Mails. 

Das ist im Grunde kein Problem, allerdings haben die Redakteure so nicht die Web-Adresse der zugrunde liegenden Seite.

**Comment by xwolfde** [comment]
Konnte ich nicht nachvollziehen. Mail kommt eigentlich immer, wenn der Haken nicht gesetzt ist das keine Mail kommen soll
