### ISSUE TITLE
Sidebar in einer neuen Seite im Code muss weg

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/FAU-Philfak#4]
<div class="sidebar-inline"></div>
z. B. hier http://test5.wordpress.webhummel.rrze.uni-erlangen.de/startseite/lehre/vom-studium-zum-beruf/fuer-arbeitgeberinnen/?preview=true&preview_id=54&preview_nonce=0bf7350712
Konsequenz: Automatischer Umbruch, wenn keine Sidebar vorhanden => automatischer Platzhalter an dieser Stelle.

**Comment by xwolfde** [comment]
done
