### ISSUE TITLE
Collapses klappen manchmal nicht automatisch zu beim aufklappen eines neuen

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/FAU-Philfak#40]
Ist nur ein Collapse in einem collapsibles, und es gibt mehrere Collapsibles, so klappt das eine Collapse beim Aufklappen eines neuen Collapse in einem Collapsibels nicht zu. Siehe Screenshot.

https://phil.cms.rrze.uni-erlangen.de/lehre/studienangebot/lehramt/lehramt-grundschule/

![bildschirmfoto 2015-05-29 um 16 07 24](https://cloud.githubusercontent.com/assets/11868989/7884314/1cceb17c-061d-11e5-8ba0-180e4cf0ebc1.png)

**Comment by xwolfde** [comment]
ja. Hatte ich gerade hier schon erläutert: https://github.com/RRZE-Webteam/FAU-Philfak/issues/35
