### ISSUE TITLE
Darstellung eines Linkbuttons

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/FAU-Philfak#41]
![bildschirmfoto 2015-06-01 um 17 08 27](https://cloud.githubusercontent.com/assets/11868989/7915925/00d93238-0881-11e5-9c6e-1d774538e14c.png)

Wird bei FAU-Person im Shortlink das extended verborgen, so sieht der Button optisch komisch aus. 

Oder muss das in fau-person (es steht hier aufgrund Theme und CSS)

**Comment by xwolfde** [comment]
Nee, passt schon. Allerdings sollte man den "Mehr Link" nur dann verwenden, wenn man die Kontakte als Liste darstellt oder wenn man den Kurzauszug darüber mit angibt.
