### ISSUE TITLE
Glossareinträge nach Kategorie sortieren

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-Philfak#42]
Wenn ich versuche, die Glossareinträge nach Kategorie zu sortieren, wird mir nichts angezeigt. 
Screenshot der Liste mit allen Einträgen:
![alle_anzeigen](https://cloud.githubusercontent.com/assets/11296947/7930692/d210880e-090a-11e5-9ee1-671af7d38f4c.png)

Screenshot der Liste nach dem Versuch, die Auswahl nach Kategorie einzuschränken:

![auswahl_einschraenken](https://cloud.githubusercontent.com/assets/11296947/7930697/dc792e90-090a-11e5-8cd2-7e7365e73b44.png)

Nach Datum kann aber sortiert werden.
Aufgetreten ist das in der Instanz www.wordpress.rrze.fau.de, auf der ja das PhilFak-Theme läuft

**Comment by xwolfde** [comment]
Kann nicht mehr nachgestellt werden. Auch auf deiner Site funktioniert es.
