### ISSUE TITLE
Menüpunkte mit individuellen Links als Unterpunkte werden nicht links in der Sidebar (=Navigation) angezeigt

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/FAU-Philfak#43]
![bildschirmfoto 2015-06-03 um 16 40 39](https://cloud.githubusercontent.com/assets/11868989/7962743/59ff3026-0a0f-11e5-9790-7e31d869a552.png)
![bildschirmfoto 2015-06-03 um 16 40 48](https://cloud.githubusercontent.com/assets/11868989/7962744/59ff682a-0a0f-11e5-8d6e-fa18a1455621.png)
HAt nichts damit zu tun: Menüeinstellungen 
![bildschirmfoto 2015-06-03 um 16 41 55](https://cloud.githubusercontent.com/assets/11868989/7962763/7d3dbf6c-0a0f-11e5-8695-d2737393f1c2.png)

da auch Frau Sell das Problem hat, ist das Theme-übergreifend.

**Comment by xwolfde** [comment]
Aber das Menü links hat doch (leider) garnichts mit den normalen Menüs zu tun!
Das bildet sich automatsich aus den Seiten, nicht aus einer Menudefinition.
(Und ja, ich finde das auch blöd und hab deswegen als Todo dies anderes zu machen. Aber so wie es jetzt ist, ist es kein Bug, sondern so gewollt.)

**Comment by xwolfde** [comment]
vgl auch https://github.com/RRZE-Webteam/FAU-Theme/issues/212

**Comment by steffigebel** [comment]
Wobei man das Menü, das links angezeigt wird, doch auch „baut“, dachte ich zumindest. Menü>Header/Haupt-Navigation>Seiten rein und rausziehen…

Bedenken sollte man hier, wenn man auch externe Portale als Nav-Punkte zulässt, dass das SEO-seitig nicht gut ist. Auf einer Website sind ja nur die Seiten wichtig, die dort angeboten werden, auf internen Seiten verlinken wäre die Alternative.

Es sollte natürlich keine Sitemap entstehen, die nur auf externe Seiten zeigt, dann wäre die Website selbst redundant.
--
Stefanie Gebel
Webmanagement
Regionales RechenZentrum Erlangen (RRZE)
Friedrich-Alexander-Universität Erlangen-Nürnberg
Martensstrasse 1, 91058 Erlangen, Germany
Tel. +49 9131 85-27807
stefanie.gebel@fau.de<mailto:stefanie.gebel@fau.de>
www.rrze.fau.de

Von: Wolfgang Wiese <notifications@github.com<mailto:notifications@github.com>>
Antworten an: RRZE-Webteam/FAU-Philfak <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: Mittwoch, 3. Juni 2015 19:46
An: RRZE-Webteam/FAU-Philfak <FAU-Philfak@noreply.github.com<mailto:FAU-Philfak@noreply.github.com>>
Cc: "Gebel, Stefanie" <stefanie.gebel@fau.de<mailto:stefanie.gebel@fau.de>>
Betreff: Re: [FAU-Philfak] Menüpunkte mit individuellen Links als Unterpunkte werden nicht links in der Sidebar (=Navigation) angezeigt (#43)


Aber das Menü links hat doch (leider) garnichts mit den normalen Menüs zu tun!
Das bildet sich automatsich aus den Seiten, nicht aus einer Menudefinition.
(Und ja, ich finde das auch blöd und hab deswegen als Todo dies anderes zu machen. Aber so wie es jetzt ist, ist es kein Bug, sondern so gewollt.)

**Comment by xwolfde** [comment]
Es gibt nur zwei Probleme:
1. Wir haben jetzt schon zu viele Menüs. Das wird unübersichtlich
2. Wenn ein Redakteuer auf einer unteren Ebene neue Seiten anlegt und diese veröffentlicht, müssen diese ja auch erreichbar sein. Da aber nur der Admin das Menu edieren könnte, wäre die Folge, daß es vergessen wird Seiten ins Menü aufzunehmen oder eben das ie Zeit zwischen Veröffentlichung und Anlegen zu lange dauert.
Daher ist auf einer unteren Ebene der Menüs es durchaus sinnvoll, daß sich ein Menu allein auf Basis der Seitenhierarchie aufbaut und nicht aufgrund eines nur durch einen Admin manuell bearbeiteten Menus.

**Comment by steffigebel** [comment]
Das Problem sehe ich auch. Und eben das mit der Sitemap. Irgenjemand sollte den Überblick behalten, sonst gibt es Monstermenüs, die keinen Sinn ergeben.
--
Stefanie Gebel
Webmanagement
Regionales RechenZentrum Erlangen (RRZE)
Friedrich-Alexander-Universität Erlangen-Nürnberg
Martensstrasse 1, 91058 Erlangen, Germany
Tel. +49 9131 85-27807
stefanie.gebel@fau.de<mailto:stefanie.gebel@fau.de>
www.rrze.fau.de

Von: Wolfgang Wiese <notifications@github.com<mailto:notifications@github.com>>
Antworten an: RRZE-Webteam/FAU-Philfak <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: Freitag, 5. Juni 2015 14:54
An: RRZE-Webteam/FAU-Philfak <FAU-Philfak@noreply.github.com<mailto:FAU-Philfak@noreply.github.com>>
Cc: "Gebel, Stefanie" <stefanie.gebel@fau.de<mailto:stefanie.gebel@fau.de>>
Betreff: Re: [FAU-Philfak] Menüpunkte mit individuellen Links als Unterpunkte werden nicht links in der Sidebar (=Navigation) angezeigt (#43)


Es gibt nur zwei Probleme:
1. Wir haben jetzt schon zu viele Menüs. Das wird unübersichtlich
2. Wenn ein Redakteuer auf einer unteren Ebene neue Seiten anlegt und diese veröffentlicht, müssen diese ja auch erreichbar sein. Da aber nur der Admin das Menu edieren könnte, wäre die Folge, daß es vergessen wird Seiten ins Menü aufzunehmen oder eben das ie Zeit zwischen Veröffentlichung und Anlegen zu lange dauert.
Daher ist auf einer unteren Ebene der Menüs es durchaus sinnvoll, daß sich ein Menu allein auf Basis der Seitenhierarchie aufbaut und nicht aufgrund eines nur durch einen Admin manuell bearbeiteten Menus.
