### ISSUE TITLE
Farbdifferenzen

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/FAU-Philfak#44]
Es wurde aus der PhilFak nochmal das Thema Farbmanual CD/CI angemerkt und nachgefragt. 

Man sieht es ganz gut anhand dieser Seite 
![bildschirmfoto 2015-06-05 um 12 06 31](https://cloud.githubusercontent.com/assets/11868989/8003889/899d20aa-0b7b-11e5-9407-020e1530716a.png)
 Die Farbcodes sind wohl nicht identisch. Ich kenne die Diskussion und Problematik darum, nicht aber so genau im Detail. Muss man aber noch mal prüfen. 
![bildschirmfoto 2015-06-05 um 12 32 39](https://cloud.githubusercontent.com/assets/11868989/8004325/3f9ac648-0b7f-11e5-95a4-36b954ac2992.png)

**Comment by xwolfde** [comment]
Web != Print :)

Die Farben ergeben sich aus der Berechnung der "harmonischen Farbwerte" ausgehend von der festgelegten Basisfarbe. (Details siehe Datei: https://github.com/RRZE-Webteam/FAU-Philfak/blob/master/css/sass/_variables.scss 
und kann hier nachgeschaut werden.
 http://paletton.com/#uid=1140u0kqhlIhItGmqp-unhvDIc9 

Das die Farbwerte für Print andere sind, ist nicht verwunderlich.

**Comment by steffigebel** [comment]
Danke!
--
Stefanie Gebel
Webmanagement
Regionales RechenZentrum Erlangen (RRZE)
Friedrich-Alexander-Universität Erlangen-Nürnberg
Martensstrasse 1, 91058 Erlangen, Germany
Tel. +49 9131 85-27807
stefanie.gebel@fau.de<mailto:stefanie.gebel@fau.de>
www.rrze.fau.de

Von: Wolfgang Wiese <notifications@github.com<mailto:notifications@github.com>>
Antworten an: RRZE-Webteam/FAU-Philfak <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: Freitag, 5. Juni 2015 14:36
An: RRZE-Webteam/FAU-Philfak <FAU-Philfak@noreply.github.com<mailto:FAU-Philfak@noreply.github.com>>
Cc: "Gebel, Stefanie" <stefanie.gebel@fau.de<mailto:stefanie.gebel@fau.de>>
Betreff: Re: [FAU-Philfak] Farbdifferenzen (#44)

Die Farben ergeben sich aus der Berechnung der "harmonischen Farbwerte" ausgehend von der festgelegten Basisfarbe. (Details siehe Datei:

**Comment by xwolfde** [comment]
Sollte @AstridSemm ggf. mit in der Doku vermerken

**Comment by AstridSemm** [comment]
Ich notiere es mir. Danke! Erfolgreiches Renovieren! 


Von Samsung Mobile gesendet

-------- Ursprüngliche Nachricht --------
Von: Wolfgang Wiese <notifications@github.com> 
Datum:05.06.2015  2:51 PM  (GMT+01:00) 
An: RRZE-Webteam/FAU-Philfak <FAU-Philfak@noreply.github.com> 
Cc: Astrid <astrid.semm@fau.de> 
Betreff: Re: [FAU-Philfak] Farbdifferenzen (#44) 

Sollte @AstridSemm ggf. mit in der Doku vermerken

**Comment by xwolfde** [comment]
In der letzten Vortragsfolie im Blog sind 3 Seiten vorhanden, die sich mit der Thematik beschäftigen.
