### ISSUE TITLE
NIcht mehr als 3 News auf der Startseite anzeigbar

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/FAU-Philfak#45]
Trotz Angabe von zb 7 News auf der Startseite in den Theme Options und Schlagwortvergabe an den News werden auf der Startseite nicht mehr als 3 News angezeigt. 

Vermute, die Änderung in den Einstellung hat keine Auswirkungen auf die Default Einstellung. 

@rvdforst evtl kannst du da mal nachsehen.

**Comment by xwolfde** [comment]
Hast du die auch richtig getaggt?

**Comment by steffigebel** [comment]
Klar: Startseite 1-4 und Allgemein

Habs auch bei Test probiert.
--
Stefanie Gebel
Webmanagement
Regionales RechenZentrum Erlangen (RRZE)
Friedrich-Alexander-Universität Erlangen-Nürnberg
Martensstrasse 1, 91058 Erlangen, Germany
Tel. +49 9131 85-27807
stefanie.gebel@fau.de<mailto:stefanie.gebel@fau.de>
www.rrze.fau.de

Von: Wolfgang Wiese <notifications@github.com<mailto:notifications@github.com>>
Antworten an: RRZE-Webteam/FAU-Philfak <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: Freitag, 5. Juni 2015 14:37
An: RRZE-Webteam/FAU-Philfak <FAU-Philfak@noreply.github.com<mailto:FAU-Philfak@noreply.github.com>>
Cc: "Gebel, Stefanie" <stefanie.gebel@fau.de<mailto:stefanie.gebel@fau.de>>
Betreff: Re: [FAU-Philfak] NIcht mehr als 3 News auf der Startseite anzeigbar (#45)


Hast du die auch richtig getaggt?

**Comment by xwolfde** [comment]
Ich schau Montag mal.. Bin ja gerade auf Urlaub (gerade Pause - renoviere gerade/das Wochenende in der Wohnung)

**Comment by steffigebel** [comment]
Na klar! Du solltest dich auch nicht angesprochen fühlen, va heute nicht ;-)
Und in der PAUSE schon gleich gar nicht, tststs…dann viel Spass beim Werkeln weiterhin und viel Erfolg!

Genieß auch die Sonne, solange sie noch scheint ;-)
--
Stefanie Gebel
Webmanagement
Regionales RechenZentrum Erlangen (RRZE)
Friedrich-Alexander-Universität Erlangen-Nürnberg
Martensstrasse 1, 91058 Erlangen, Germany
Tel. +49 9131 85-27807
stefanie.gebel@fau.de<mailto:stefanie.gebel@fau.de>
www.rrze.fau.de

Von: Wolfgang Wiese <notifications@github.com<mailto:notifications@github.com>>
Antworten an: RRZE-Webteam/FAU-Philfak <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: Freitag, 5. Juni 2015 14:47
An: RRZE-Webteam/FAU-Philfak <FAU-Philfak@noreply.github.com<mailto:FAU-Philfak@noreply.github.com>>
Cc: "Gebel, Stefanie" <stefanie.gebel@fau.de<mailto:stefanie.gebel@fau.de>>
Betreff: Re: [FAU-Philfak] NIcht mehr als 3 News auf der Startseite anzeigbar (#45)


Ich schau Montag mal.. Bin ja gerade auf Urlaub (gerade Pause - renoviere gerade/das Wochenende in der Wohnung)

**Comment by xwolfde** [comment]
wird im nächsten update gefixtet sein
