### ISSUE TITLE
Möglichkeit via Shortcodes Alt- und Titel-Tags einzufügen?

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/FAU-Philfak#46]
Es wäre gut, wenn man bei Shortcodes zb bei Fau-Karte Alt- und/oder titel-Tags angeben könnte, oder ist das bereits irgendwie integriert, falls die Karte nicht angezeigt werden kann? ZB Wie man auch width= oder height= angeben kann als Parameter. 

Wäre auch relevant bei Videos oder Galerien (wobei man den Bildern zwar Alt-Tag aber keinen Titel-Tag geben kann (außer via html-Editor))

Bzw. ist das überhaupt eine berechtigte Frage oder total Nonsense? 

Evtl sind das mehrere Issues in einem. Könnten wir mal im Jour-fixe besprechen, falls relevant.

**Comment by xwolfde** [comment]
Bitte jeweils bei den einzelnen Plugins reintragen. Hier nutzt das nichts, wenn es kein Shortcode des Themes betrifft. Teilwesie ist es ja möglich. d.h. bitte dann auch genauer.
