### ISSUE TITLE
Beiträge/Kategorien im Portalmenü nicht mehr erreichbar

### ISSUE THREAD

**Issue by FlorianFiller** [RRZE-Webteam/FAU-Philfak#47]
Seit gestern/vorgestern ist die im Portalmenü verlinkte Beitragskategorie nicht mehr erreichbar/anklickbar - auch eine neue Einbindung der Kategorie in das Portalmenü behebt das Problem nicht. Die Einbindung in das Haupt-Menü (Header) funktioniert aber noch.
Aktuell eingebunden: Kategorie "Allgemein" unter "Infocenter" als "Aktuelles".

**Comment by xwolfde** [comment]
wurde im Treffen geklärt

**Comment by xwolfde** [comment]
Nochmal checken. Aber tendiere zu einem Miussverständnis. Menüs sollten eigentlich immer nur auf statische Seiten verweisen.

**Comment by xwolfde** [comment]
War was meiner Erinnerung anderes: Bei Beiträgen (nicht Seiten) müssen die Kategorien über die Widget-Funktion eingeblendet werden. Dabei werden leider nur die Oberkategorien gezeigt
