### ISSUE TITLE
Reihenfolge Kontakte in der Sidebar

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/FAU-Philfak#48]
Es muss in der Sidebar möglich sein, die Reihenfolge bei der Personenauswahl aus der Dropdown-Box zu bestimmen. Bisher wird nach Alphabet des VORnamens geordnet.

**Comment by xwolfde** [comment]
Das würde eine extra Auswahlfunktion erfordern, die allerdings wieder die Bedienung für unbedarftere Nutzer wieder verkomplizieren würde.
Gleichzeitig ist es gewollt im Design, dass dort nur ein Kontakt steht und nicht zwei oder mehr.
Von daher will ich die unerwünschte Merhfachanzeige nicht auch noch unterstützen durch eine neue Funktion.
Benutzer, dei wissen was sie tun sollen stattdessen den Shortcode in den textbereien oben oder unten einfügen. Das sollte gehen. Wenn es nicht geht, dann ist da ein Bug, der gesondert gelöst werden sollte.
