### ISSUE TITLE
Personenanzeige in Sidebar

### ISSUE THREAD

**Issue by endv02** [RRZE-Webteam/FAU-Philfak#5]
Issue von cibsell war bei fau-person falsch, kommt durch die Personenanzeige im Theme:

Hallo,

wenn ich bei Personen eine Person anlege und unter "Eigenschaften" die Postadresse angebe, dann erscheint diese Adresse in der Sidebar ohne Zeilenumbruch, siehe Screenshot. Gebe ich br ein, wird der Code in Text umgewandelt und kein Zeilenumbruch gemacht.

![fc900eac-df83-11e4-88bb-2fe0d543f767](https://cloud.githubusercontent.com/assets/5851793/7088703/51cf2b8e-df96-11e4-9829-fce4a2282372.png)

**Comment by xwolfde** [comment]
Wahrscheinlich eine alte Version - ist bei meiner Testkiste nämnlich schon repariert.
