### ISSUE TITLE
Problem der Akkordeon auch bei nur 2 Spalten

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/FAU-Philfak#50]
Das Akkordeon braucht bei Seiten mit Navigation links 2 Spalten, allerdings beim Standardtemplate ohne Navigation links und mit Sidebar nimmt es sich ganze 3 Spalten. Das sollte so nicht sein. Test hier https://phil.cms.rrze.uni-erlangen.de/test-collapsibels/

![bildschirmfoto 2015-06-15 um 08 30 00](https://cloud.githubusercontent.com/assets/11868989/8154296/07ea6aa2-1339-11e5-9aac-aac3e9bf8995.png)

Auf Portalseiten tritt das Problem nicht auf. Hier werden vom Akkordeon 2 Spalten belegt und die Sidebar ist problemlos anzeigbar. Test hier https://phil.cms.rrze.uni-erlangen.de/test-collapsibles-2/
![bildschirmfoto 2015-06-15 um 08 36 29](https://cloud.githubusercontent.com/assets/11868989/8154369/ab2c2d72-1339-11e5-8b55-bc15bc32ff3c.png)

**Comment by xwolfde** [comment]
Beim nächsten Update gefixt
