### ISSUE TITLE
Wie stellt man Bilder in für Portalsmenüs ein, wenn die Links dort auf externe Seiten gehen?

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/FAU-Philfak#52]
Man will also praktisch ein Portalmenü mit zb 4 Punkten mit je einem Bildchen angezeigt. Klick darauf: Externe Website. 

Frage also: Wo kommen die Bilder her? Oder wie kriege ich die Bidler aus der Mediathek in die Portalmenüs?

@xwolfde wichtig aktuell für PhilFak ;-)

**Comment by xwolfde** [comment]
Garnicht. Im Menü eines Webauftritts gehören *niemals* Links zu externen Seiten.

Möglicherweise möchtest du aber stattdessen "Bildlinks" nutzen.

**Comment by xwolfde** [comment]
@AstridSemm bitte in doku

**Comment by AstridSemm** [comment]
Kommt, ist schon für https://www.wordpress.rrze.fau.de/fuer-autoren/seiten/die-portalseite/ vorgesehen. Danke für den reminder!

**Comment by FlorianFiller** [comment]
Nur als kleiner Beitrag ein Screenshot von der fau.de-Startseite:
![fau_de_portalmenu_extern](https://cloud.githubusercontent.com/assets/12810141/8229428/ecebceb4-15b6-11e5-8e7f-0dc0c9ce5795.png)

Die "Menüpunkte" mit dem kleinen blauen Pfeil rechts oben gehen auf externe Seiten - irgendwie ist es also wohl möglich.

Für die Phil-Fak-Seite haben wir das aber aktuell über Bildlinks gelöst. Interessant wäre die Option aber trotzdem.

**Comment by steffigebel** [comment]
Hier kommt die Lösung:
![bildschirmfoto 2015-06-18 um 13 15 08](https://cloud.githubusercontent.com/assets/11868989/8230035/9e45220a-15bc-11e5-9c27-0e5457b2143a.png)

**Comment by AstridSemm** [comment]
Der Vollständigkeit halber melde ich mal Vollzug: Beschreibung des Einfügens von Bildlinks: https://www.wordpress.rrze.fau.de/redaktion/bildlinks/, die Beschreibung, wie man Bildlinks als Menüpunkte definiert, ist dann bei den Menüs.
