### ISSUE TITLE
Layout Kontakte im Contentbereich bei Seiten ohne Navi

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/FAU-Philfak#54]
Kontaktboxen sollten im Content-Bereich grundsätzlich nur eine max. Spaltenbreite von 2 Spalten haben. bzw. sich an weitere Spalten anpassen können, auch wenn keine Navi links steht. 
![bildschirmfoto 2015-06-17 um 09 05 03](https://cloud.githubusercontent.com/assets/11868989/8201346/557bc4f8-14d0-11e5-9432-51e285a72c50.png)

**Comment by xwolfde** [comment]
Nö, ist so nicht vorgesehen vom Design

**Comment by xwolfde** [comment]
Falsch verstanden. Bug ist die Überlagerung.
Ist in der nächsten Version gefixt.
