### ISSUE TITLE
Schattenwurf/Passpartout für normale Bilder

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Philfak#57]
Via CSS-Klasse es ermöglichen, dass man bei normalen Bildern ein Passpartout oder ein stärker ausgeprägten Schattenwurf haben kann.

**Comment by xwolfde** [comment]
Bitte dokumentieren:
http://test4.wordpress.webhummel.rrze.uni-erlangen.de/test-portal/tests-mit-bildern/

**Comment by xwolfde** [comment]
Einzubindende Klassen bei den Bild-CSS sind:

"shadow"
"thickborder"

**Comment by AstridSemm** [comment]
Ist ebenfalls dokumentiert als Tipp, vorläufig auf der Testinstanz, weil ich noch auf Rückmeldung zum Vorgehen warte. Wird dann in die Hauptinstanz gepastet.
