### ISSUE TITLE
Überlagerung auf der Startseite: Content-Pfeil vs. Bühnenmenü

### ISSUE THREAD

**Issue by FlorianFiller** [RRZE-Webteam/FAU-Philfak#58]
Der "Content-Pfeil" auf der Startseite überlagert den untersten Link im Menü "Bühne1" (PhilFak-Theme) - siehe Rahmen um den Pfeil:
![content_startseite](https://cloud.githubusercontent.com/assets/12810141/8250659/fc4c9dba-1675-11e5-8373-9e1fd960cc18.png)

Auf fau.de tritt das vergleichbare Problem auf - siehe Mauszeiger und URL unten links:
![content_startseite_fau_de](https://cloud.githubusercontent.com/assets/12810141/8250677/2315e546-1676-11e5-92d1-a37bd283b656.png)

**Comment by xwolfde** [comment]
Hm..  mit Firefox und Safari unter MacOS sehe ich die garnicht

**Comment by FlorianFiller** [comment]
Bei mir ist das (in allen Browsern) abhängig vom Zoomfaktor ...

**Comment by xwolfde** [comment]
ah.... bei einem windows-rechner kann ich es gerade nachstellen, wenn ich die seite einen zoomfaktor gebe, der bewirkt, dass dort unten ausreichend platz ist...
(was für ein Pfusch ist denn das?)

**Comment by xwolfde** [comment]
Ah, jetzt. Es erscheint nur bei
@media (min-width: 768px) and (min-height: 700px) and (max-height: 900px) { }

**Comment by xwolfde** [comment]
Ok, hab es geändert. Da es aber  unschön aussieht und eigentlich unnütz ist, hab ich es Optional einschaltbar gemacht (Design->Theme Options->Erweitert), so daß es nur erscheint, wenn man es vorher eingeschaltet hat.
Ist im nächsten Update enthalten.
