### ISSUE TITLE
Doku: Farben für Sidebar/Widget-Menu/Kategorien

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Philfak#59]
Für die Doku:

um in der News-Sidebar bei Nutzung des Menu-Widgets Farben zu nutzen, sind folgende Klassen zu verwenden:
![farben-widget-menu](https://cloud.githubusercontent.com/assets/1070669/8280795/4f4c6406-18e1-11e5-883e-a9ff4b60deee.png)

Klassen sind:
philfak, rwfak, medfak, natfak, techfak, default, fau

![cssklassen-setzen-menu](https://cloud.githubusercontent.com/assets/1070669/8280835/ca4f7526-18e1-11e5-9368-86508533d657.png)

Screenshot liegen wie üblich auch im Gitlab Projekt Rollout unter Screenshots

**Comment by AstridSemm** [comment]
Da staune ich jetzt, denn bei mir sieht das alles irgendwie anders aus (alfirin.test.rrze.uni-erlangen.de):
![bildschirmfoto 2015-09-03 um 11 30 23](https://cloud.githubusercontent.com/assets/11296947/9655133/5543e870-522f-11e5-9af2-2c3f58644982.png)

**Comment by AstridSemm** [comment]
Wunderbar, das ist geklärt (der Doku wegen: Mann muss in den Optionen die CSS-Klassen anhaken). Nächste Frage @xwolfde : Warum ist auf meiner Testinstanz die PhilFak hellblau mit dunkelblauer Schrift?
![bildschirmfoto 2015-09-03 um 12 19 37](https://cloud.githubusercontent.com/assets/11296947/9656113/3c2668a2-5236-11e5-8e69-a0423f290355.png)

**Comment by xwolfde** [comment]
Das ist ein Bug, den ich gleich behebe

**Comment by xwolfde** [comment]
In der nächsten Version behoben.

**Comment by AstridSemm** [comment]
Wirst du mir wohl keine Issues zumachen, die ich noch brauche? ^^

**Comment by xwolfde** [comment]
Und? Schon dokumentiert?

**Comment by AstridSemm** [comment]
Nee, aber solange das so aussieht wie im alfirin zur Zeit, würde ich die Doku auch nicht veröffentlichen. 
![bildschirmfoto 2016-04-22 um 14 39 29](https://cloud.githubusercontent.com/assets/11296947/14741664/3b313634-0898-11e6-851b-32826fea55b9.png)

**Comment by AstridSemm** [comment]
Es sieht übrigens immer noch nicht anders aus, wollte ich mal gesagt haben.

**Comment by AstridSemm** [comment]
Es hat sich noch nichts daran geändert; solange das Menü so aussieht, kann ich es kaum dokumentieren bzw. empfehlen.

**Comment by xwolfde** [comment]
fixed im nächsten update

**Comment by AstridSemm** [comment]
Dokumentiert ist es schon einmal, nachdem das jetzt repariert ist; allerdings kommt in den Beitrag noch einiges andere rein, deshalb ist er noch nicht online (ich brauche dazu auch das Kalenderplugin). Wird dann unter https://www.wordpress.rrze.fau.de/2016/09/16/tipp-die-news-sidebar-nutzen zu erreichen sein.
