### ISSUE TITLE
Kann man Seiten und Beiträge duplizieren?

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/FAU-Philfak#63]
In der Schulung WP FAU.de gab es das Thema "Erstellen einer neuen Version einer Seite". Es stellt sich die Frage, ob Seiten kopiert werden können, da nur wenige Änderungen vorgenommen werden sollen für eine neue Seite. ZB wäre das relevant auch für Kontakte von der gleichen Abteilung, Einrichtung, Adresse, etc, die sich nur im Namen und Raum unterscheiden. 

Weder als Redakteur noch Admin noch Autor sehe ich eine solche Funktion im Backend.

**Comment by xwolfde** [comment]
Bei Verwendung des Plugins zum redaktionellen Workflow welches bei der ZUV eingesetzt wird, ist eine Funktion enthalten, bei der eine Seite kopiert wird um daraus eine neue Version zu erstellen.
Dies ist aber eine Sache die nur speziell bei Nutzung des redaktionellen Workflows dort funktioniert und gedacht ist. Für normale Nutzung ohne redaktionellen Workflow ist das nicht gedacht.
Aber auch dann wird es gerade bei Kontakten nicht funktionieren, da diese ja auch anders verwaltet werden.
