### ISSUE TITLE
Doku und Optionsbeschreibung Startseite

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Philfak#67]
Bei der Beschreibung der Startseiten-News deutlich hinschreiben, daß maximal startseite 1, startseite2, startseite3 verwendet werden können.

**Comment by AstridSemm** [comment]
Die Seiten https://www.wordpress.rrze.fau.de/administration/startseite/ und https://www.wordpress.rrze.fau.de/administration/startseite-fakultaet/ entsprechend angepasst.
