### ISSUE TITLE
Bug: Funktionalität Fakultätslogo ist verkehrt herum

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Philfak#68]
...auf der Startseite klickbar, auf Unterseiten nicht klickbar (und führt somit von diesen nicht auf die Startseite der Fakultät).

**Comment by AstridSemm** [comment]
Ich habe mir das jetzt mal auf https://phil.cms.rrze.uni-erlangen.de/ angesehen - da stimmt es. Auf der Startseite ist das Logo nicht anklickbar, auf den Unterseiten ist es anklickbar und verlinkt zurück auf die Startseite. Wo hast du das denn ausprobiert?

**Comment by wrkb** [comment]
Shame on me, da war was nicht fertigkonfiguriert in unserem Spielwordpress und ich hab mich irreführen lassen. Danke fürs gucken und schnell schließen, bevor es noch jemand merkt :D
