### ISSUE TITLE
Wohin verschwinden die Kommentare?

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-Philfak#7]
Man kann zwar kommentieren (auch wenn nicht ganz klar ist, wie das geht, denn auch zum Kommentieren finde ich unter dem Beitrag keinen Link), die Kommentare werden aber nicht angezeigt. Siehe: http://test5.wordpress.webhummel.rrze.uni-erlangen.de/2015/03/05/hallo-welt/
Schreenshot: 
![bildschirmfoto 2015-04-15 um 09 28 32](https://cloud.githubusercontent.com/assets/11296947/7154045/2432061e-e352-11e4-86d2-f84e7064e19c.png)

**Comment by xwolfde** [comment]
Ok, fixed - jetzt können Kommentare erscheinen :)
