### ISSUE TITLE
Seitenlayout

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/FAU-Philfak#70]
Zur Veranschaulichung was ich meine: https://www.phil.fau.de/internationales/internationales-buero/
Hier sind Leerräume sehr auffällig. Im bearbeitungsmodus sind sowohl "visuell" als auch "Text" keine Leerzeilen gesetzt. Wenn ich allerdings im Browser das Element untersuche, sehe ich 2 p-Tags untereinander, die den Leerraum erzeugen. 

Das ist komisch und war beim erstellen der Seite anders. Warum ist das so und wie kriege ich die weider weg?
![bildschirmfoto 2015-07-15 um 12 59 08](https://cloud.githubusercontent.com/assets/11868989/8697015/cd864c16-2af1-11e5-8f91-68ff7ee8d793.png)
![bildschirmfoto 2015-07-15 um 12 59 19](https://cloud.githubusercontent.com/assets/11868989/8697016/cd8668f4-2af1-11e5-9e52-b9e5da2404ec.png)

**Comment by AstridSemm** [comment]
Habe es mir auf dem Handy angesehen, dort keine Auffälligkeiten. Odrr ist das schon behoben? 


Von Samsung Mobile gesendet

-------- Ursprüngliche Nachricht --------
Von: Steffi <notifications@github.com> 
Datum:15.07.2015  1:02 PM  (GMT+01:00) 
An: RRZE-Webteam/FAU-Philfak <FAU-Philfak@noreply.github.com> 
Betreff: [FAU-Philfak] Seitenlayout (#70) 

Zur Veranschaulichung was ich meine: https://www.phil.fau.de/internationales/internationales-buero/
Hier sind Leerräume sehr auffällig. Im bearbeitungsmodus sind sowohl "visuell" als auch "Text" keine Leerzeilen gesetzt. Wenn ich allerdings im Browser das Element untersuche, sehe ich 2 p-Tags untereinander, die den Leerraum erzeugen.

Das ist komisch und war beim erstellen der Seite anders. Warum ist das so und wie kriege ich die weider weg?

**Comment by xwolfde** [comment]
Falsche Benutzung durch Anwender. Accordions sind Accordions und nicht einfach als Trennlinien zu nutzen!
