### ISSUE TITLE
Fehlermeldung im Backend bei Beitragsoptionen

### ISSUE THREAD

**Issue by endv02** [RRZE-Webteam/FAU-Philfak#71]
statt der Anzeige der nötigen Kategorie für die Bühnendarstellung kommt ein Notice, wenn keine Kategorie existiert:
Notice: Undefined property: WP_Error::$name in /srv/www/vhosts/krach.rrze.uni-erlangen.de/websource/wp-content/themes/FAU-Philfak/functions/custom-fields.php on line 150

**Comment by xwolfde** [comment]
fixed in der nächsten version
