### ISSUE TITLE
Kalender ohne automatische Zeitumstellung

### ISSUE THREAD

**Issue by FlorianFiller** [RRZE-Webteam/FAU-Philfak#74]
Termine, die nach der Zeitumstellung (in diesem Jahr 24./25.10.) liegen, werden bei den Veranstaltungen auf der Startseite mit der falschen (nicht umgestellten) Zeit angezeigt, wenn sie im Outlook-/ICS-Kalender mit der (dann) korrekten Zeit angelegt sind.
Kann man das dem PlugIn "beibringen"?

Veranstaltungskalender auf der Hompage:
![zeitumstellung_hp](https://cloud.githubusercontent.com/assets/12810141/9788034/a1cef048-57c7-11e5-80e8-3b3ade7c0722.png)
Kalender in Outlook:
![zeitumstellung_outlook](https://cloud.githubusercontent.com/assets/12810141/9788035/a6d8451c-57c7-11e5-8ebd-ebcfa78a3c55.png)

So müssten wir Veranstaltungen falsch in den Kalender eintragen, damit sie auf der Homepage richtig angezeigt werden - und am 25.10. alle manuell ändern.

(eventuell wäre der issue in fau-events besser aufgehoben - wenn ja, dann bitte verschieben)

**Comment by xwolfde** [comment]
@rvdforst Dein Fall. Schaust du da bitte?

**Comment by rvdforst** [comment]
Das ist kein Problem des Plugins. Wahrscheinlich wurde dem ICAL Feed die Zeitzone UTC +1 bzw. "W. Europe Standard Time" zugewiesen statt "Europe/Berlin". Also es geht um die richtige Einrichtung eines ICAL Feed. Der folgende Artikel beschreibt das grundsätzliche Verfahren: http://support.microsoft.com/?kbid=507644
