### ISSUE TITLE
Gewünscht: Link zu bestimmten geöffneten Akkordeonlaschen

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/FAU-Philfak#77]
Es wäre gut, wenn die Themes so weiterentwickelt würde, dass ein Link ähnlich von Sprunkmarken zu offenen bestimmten Akkordeonlaschen möglich ist. Das würde den uSer auf bestimmte Themen führen und er müsste nicht suchen. Jede Lasche hat, wenn man mit der Maus über diese fährt, einen Zusatz in der URL z. B. /#collapse_2 diese Url greift aber nicht, wenn ich sie als Link verwende. Der Browser liest es immer als URL ohne /#collapse_2.

**Comment by xwolfde** [comment]
Wird in der nächsten Version erledigt sein, test erstmal in FAU Einrichtungen Theme in Kürze
