### ISSUE TITLE
 Listenformatierung im Text-Widget

### ISSUE THREAD

**Issue by pdees** [RRZE-Webteam/FAU-Philfak#78]
Das Text-Widget setzt Überschriften und Absätze in einer kleineren Schriftgröße als in der normalen Textausgabe, was ich auch richtig finde. Aufzählungen werden aber in normaler Schriftgröße gesetzt, das müsste angepasst werden (siehe z.B. hier: https://economics-en.cms.rrze.uni-erlangen.de/)

**Comment by xwolfde** [comment]
Sollte mit dem kommenden Update behoben werden.
