### ISSUE TITLE
Sprachversion

### ISSUE THREAD

**Issue by pdees** [RRZE-Webteam/FAU-Philfak#79]
Die Sprachdatei funktioniert offensichtlich nur mit der Spracheinstellung "English (United States)", nicht mit "Englisch (UK)". Das gibt einen Konflikt mit dem CRIS-Plugin, wo die Spracheinstellung nur umgekehrt funktioniert (dort ist das Issue auch offen). Zumindest eine Angleichung wäre wünschenswert (betrifft möglicherweise auch alle anderen Versionen des FAU-Designs)

**Comment by xwolfde** [comment]
Mit dem Sprachendienst war meiner Erinnung nach mal abgesprochen, dass Übersetzungen prioritär in Englisch-US erfolgen sollen. Wenn aus CRIS das anders kommt,  müssen wir es da mal an den Projektleiter geben... Gut, daß Sie es da schon eingetragen haben.

Wie auch immer: Im kommenden Update des Themes (morgen!) wird  als schnelle Lösung erstmal die Sprachdatei von en-US auf en-GB kopiert, so daß es dann soweit behoben sein sollte.
