### ISSUE TITLE
Formatierungen in Tabellen

### ISSUE THREAD

**Issue by pdees** [RRZE-Webteam/FAU-Philfak#80]
Bei Listen innerhalb von Tabellenzellen formatiert das Theme diese farbig, während Text üblicherweise schwarz ist. Bei Absatzumbrüchen in Tabellenzellen wird die Schrift gegenüber der Textformatierung ohne Absatzmarkierung vergrößert.

**Comment by xwolfde** [comment]
Sollte mit dem kommenden Update behoben werden
