### ISSUE TITLE
Platzierung Sidebar

### ISSUE THREAD

**Issue by pdees** [RRZE-Webteam/FAU-Philfak#82]
Möglicherweise ist beim Theme-Update etwas schiefgegangen: Zumindest auf unseren Homepages (economics.phil.de und economics.phil.eu), aber auch bei https://www.phil.fau.de/news/allgemein/forschung/ drückt es die Sidebar nach unten. Wahrscheinlich ist die Content-Spalte versehentlich zu breit geworden.

**Comment by xwolfde** [comment]
Danke für die schnelle Rückmeldung

**Comment by xwolfde** [comment]
Gefixt
