### ISSUE TITLE
Kommentare überarbeiten?

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-Philfak#9]
Es ist das eine oder andere zu diskutieren; siehe screenshot, zweiter Kommentar.
![bildschirmfoto 2015-04-16 um 15 36 42](https://cloud.githubusercontent.com/assets/11296947/7181967/9c457152-e44e-11e4-9a44-c8d0764b5122.png)

**Comment by xwolfde** [comment]
Ist Absicht so :palm_tree:
